version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rest
      MYSQL_USER: sa
      MYSQL_PASSWORD: mysqlpassword
    ports:
      - "3306:3306"
    command: --general-log=1 --general-log-file=/etc/mysql/conf.d/general.log
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_logs:/etc/mysql/conf.d

volumes:
  db_data:
