server:
  port: ${SERVER_PORT:8080} # 만약 환경변수가 없으면 기본 8080 사용

spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: coffeeproject
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false
  # 시크릿 키
  jwt:
    secret: b075fb05b988c8e6e1065f35e6d6b992b68cc216d2265aac73e088d9a3ffdf7fecbd554c8ba0cd7c8e45a7e32b7aede0e72b6a2788bdc5518b8b313473f3b1a0



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
