name: PR Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "main", "develop" ]
    types: [opened, reopened, ready_for_review, synchronize]
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "frontend/**"

jobs:
  springboot-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Navigate to backend directory
        run: cd backend

      - name: Set up JDK 23
        uses: actions/setup-java@v1
        with:
          java-version: 23

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: backend

      - name: Test with Gradle
        run: ./gradlew test
        working-directory: backend

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'backend/**/build/test-results/test/TEST-*.xml'
